services:
  api:
    container_name: evolution_api
    image: evolution/api:local
    build: .
    restart: always
    ports:
      - 8080:8080
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - marcai-network
    env_file:
      - .env
    expose:
      - 8080
    depends_on:
      redis:
        condition: service_started
      evolution-postgres:
        condition: service_healthy

  redis:
    container_name: evolution_redis
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - evolution_redis:/data
    networks:
      - marcai-network
    command: redis-server --appendonly yes

  evolution-postgres:
    container_name: evolution_postgres
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=evolution
      - POSTGRES_USER=evolution
      - POSTGRES_PASSWORD=evolution
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - marcai-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U evolution"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  evolution_redis:
  postgres_data:
  evolution_instances:


networks:
  marcai-network:
    name: marcai-network
    driver: bridge
    external: true
